import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireSession, requirePermission, ApiError } from "@/lib/tenant";
import { parseRange } from "@/lib/analytics-range";
import { buildAuditWhere, actionLabel, entityLabel, describeChange } from "@/lib/audit-query";
import { buildXlsx, type Cell } from "@/lib/xlsx-lite";

// Reads the signed-in session, so it must never be pre-rendered at build time.
export const dynamic = "force-dynamic";

const TZ = process.env.APP_TIMEZONE || "Africa/Lagos";
const MAX_ROWS = 10_000;
const BATCH = 2000;
const fmt = new Intl.DateTimeFormat("en-CA", { timeZone: TZ, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false });
const dt = (d: Date) => fmt.format(d).replace(", ", " ");

/** Excel download of the audit log for the chosen dates/filters. Super Admin only, date-bounded, capped at 10,000 rows. */
export async function GET(req: NextRequest) {
  try {
    const ctx = await requireSession();
    requirePermission(ctx, "ADMIN");

    const sp = req.nextUrl.searchParams;
    const from = sp.get("from");
    const to = sp.get("to");
    const range = from && to ? parseRange({ range: "custom", from, to }) : parseRange({ range: "7" });
    const where = buildAuditWhere(ctx.tenantId, { action: sp.get("action") || undefined, entity: sp.get("entity") || undefined, actor: sp.get("actor") || undefined }, range);

    // Same per-person limit as ticket downloads (they share the "exported" audit action).
    const recent = await prisma.auditLog.count({
      where: { tenantId: ctx.tenantId, actorId: ctx.userId, action: "exported", createdAt: { gte: new Date(Date.now() - 10 * 60_000) } },
    });
    if (recent >= 6) throw new ApiError(429, "You've downloaded several reports in the last few minutes. Please wait a little and try again.");

    const members = await prisma.membership.findMany({ where: { tenantId: ctx.tenantId }, select: { user: { select: { id: true, name: true } } } });
    const names = new Map(members.map((m) => [m.user.id, m.user.name]));

    const rows: Cell[][] = [];
    let cursor: string | undefined;
    let truncated = false;
    while (rows.length < MAX_ROWS) {
      const take = Math.min(BATCH, MAX_ROWS - rows.length + 1);
      const batch = await prisma.auditLog.findMany({
        where,
        orderBy: [{ createdAt: "desc" }, { id: "desc" }],
        take,
        ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
        select: { id: true, actorId: true, action: true, entity: true, entityId: true, before: true, after: true, createdAt: true },
      });
      if (batch.length === 0) break;
      for (const r of batch) {
        if (rows.length >= MAX_ROWS) {
          truncated = true;
          break;
        }
        rows.push([dt(r.createdAt), r.actorId ? names.get(r.actorId) ?? "Former user" : "System / API", actionLabel(r.action), entityLabel(r.entity), r.entityId, describeChange(r.before, r.after, 1000)]);
        cursor = r.id;
      }
      if (truncated || batch.length < take) break;
    }

    const user = await prisma.user.findUnique({ where: { id: ctx.userId }, select: { name: true } });
    const file = buildXlsx([
      { name: "Audit log", rows: [["When", "Who", "Action", "On", "Record ID", "Details"], ...rows], colWidths: [18, 24, 26, 18, 28, 90] },
      {
        name: "About this report",
        colWidths: [22, 70],
        rows: [
          ["Item", "Value"],
          ["Report", "CX360 audit log"],
          ["Between", `${range.from} to ${range.to}`],
          ["Entries in this file", rows.length],
          ["Note", truncated ? `Limited to the first ${MAX_ROWS.toLocaleString()} entries — narrow the dates to get the rest.` : "Complete for the selected filters."],
          ["Generated by", user?.name ?? ""],
          ["Generated at", `${dt(new Date())} (${TZ})`],
        ],
      },
    ]);

    try {
      await prisma.auditLog.create({
        data: { tenantId: ctx.tenantId, actorId: ctx.userId, action: "exported", entity: "AuditExport", entityId: ctx.userId, after: { from: range.from, to: range.to, rows: rows.length, truncated } },
      });
    } catch (e) {
      console.error("export audit failed", e);
    }

    return new NextResponse(new Uint8Array(file), {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="cx360-audit-log-${range.from}_to_${range.to}.xlsx"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    if (err instanceof ApiError) return NextResponse.json({ error: err.message }, { status: err.status });
    console.error(err);
    return NextResponse.json({ error: "Internal error" }, { status: 500 });
  }
}
